services:
  db:
    image: linuxserver/mariadb:latest
    container_name: ktor-db
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Madrid
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ktor_db
      MYSQL_USER: ktor_user
      MYSQL_PASSWORD: ktor_password
    volumes:
      - ./mysql_data:/config
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: ktor-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  ktor-app:
    build: .
    container_name: ktor-api
    restart: always
    ports:
      - "8001:8080"
    depends_on:
      - db
