services:
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: ktor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    env_file:
      - .env

  adminer:
    image: adminer
    container_name: ktor-adminer
    restart: always
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"
    depends_on:
      - db
