services:
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: ktor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT:-3306}:${MYSQL_CONTAINER_PORT:-3306}"
    networks:
      - ktor-network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: ktor-adminer
    restart: always
    ports:
      - "${ADMINER_HOST_PORT:-8080}:${ADMINER_CONTAINER_PORT:-8080}"
    networks:
      - ktor-network
    depends_on:
      - db

  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ruser215/api-spotifake:latest
    container_name: ktor-app
    restart: always
    ports:
      - "${KTOR_HOST_PORT:-8001}:8001"
    networks:
      - ktor-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_HOST_PORT=3306
    volumes:
      - ./archivos:/app/archivos

networks:
  ktor-network:
    driver: bridge
