version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: ktor-db
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    networks:
      - ktor-network
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: ktor-adminer
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    restart: always
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"
    networks:
      - ktor-network
    depends_on:
      - db

  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor-app
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    restart: always
    ports:
      - "${KTOR_HOST_PORT}:8001"
    networks:
      - ktor-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    profiles:
      - app

networks:
  ktor-network:
    driver: bridge
