services:
  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: ktor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ktor_db
      MYSQL_USER: ktor_user
      MYSQL_PASSWORD: ktor_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: ktor-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
