version: '3.8'

services:
  db:
    image: biarms/mysql:5.7
    container_name: ktor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}"
    networks:
      - ktor-network
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  adminer:
    image: adminer
    container_name: ktor-adminer
    restart: always
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"
    networks:
      - ktor-network
    depends_on:
      - db

  ktor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ktor-app
    restart: always
    ports:
      - "${KTOR_HOST_PORT}:8001"
    networks:
      - ktor-network
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db

networks:
  ktor-network:
    driver: bridge
